schema_version = "1.1"
artifacts = []

[task]
name = "terminal-bench/crack-7z-hash"
description = "Evaluates the ability to crack a password-protected 7z archive using John the Ripper and extract secret contents."
keywords = ["decrypt", "security", "file-operations"]
[[task.authors]]
name = "Jan-Lucas Uslu"
email = "uslu@stanford.edu"

[metadata]
author_name = "Jan-Lucas Uslu"
author_email = "uslu@stanford.edu"
difficulty = "medium"
category = "security"
tags = ["decrypt", "security", "file-operations"]
expert_time_estimate_min = 5.0
junior_time_estimate_min = 10.0

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 600.0
docker_image = "alexgshaw/crack-7z-hash:20251031"
cpus = 1
memory_mb = 4096
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
