schema_version = "1.1"
artifacts = []

[task]
name = "terminal-bench/rstan-to-pystan"
description = "Evaluates the ability to convert an RStan Gaussian Process script to functionally equivalent PyStan 3.10.0 code, including complex installation, hyperparameter mapping, and numerical verification of posterior estimates."
keywords = ["pystan", "rstan", "gaussian-process", "data-science"]
[[task.authors]]
name = "Zhiwei Xu"
email = "zhiweixu@umich.edu"

[metadata]
author_name = "Zhiwei Xu"
author_email = "zhiweixu@umich.edu"
difficulty = "medium"
category = "data-science"
tags = ["pystan", "rstan", "gaussian-process"]
expert_time_estimate_min = 180.0
junior_time_estimate_min = 2880.0
custom_docker_compose = true
moved_workdir_from_compose_to_dockerfile = true

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 600.0
docker_image = "alexgshaw/rstan-to-pystan:20251031"
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
